/* tslint:disable */
/* eslint-disable */
/**
 * Payment Processor Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ConditionAction = {
    Disallow: 'DISALLOW'
} as const;
export type ConditionAction = typeof ConditionAction[keyof typeof ConditionAction];


export function ConditionActionFromJSON(json: any): ConditionAction {
    return ConditionActionFromJSONTyped(json, false);
}

export function ConditionActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConditionAction {
    return json as ConditionAction;
}

export function ConditionActionToJSON(value?: ConditionAction | null): any {
    return value as any;
}

