/* tslint:disable */
/* eslint-disable */
/**
 * Payment Processor Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface PaymentprocessorPerformRefundRequest
 */
export interface PaymentprocessorPerformRefundRequest {
    /**
     * 
     * @type {string}
     * @memberof PaymentprocessorPerformRefundRequest
     */
    'tenantId': string;
    /**
     * 
     * @type {string}
     * @memberof PaymentprocessorPerformRefundRequest
     */
    'refundId': string;
    /**
     * 
     * @type {PaymentprocessorPayment}
     * @memberof PaymentprocessorPerformRefundRequest
     */
    'payment': PaymentprocessorPayment;
    /**
     * 
     * @type {PaymentprocessorMoney}
     * @memberof PaymentprocessorPerformRefundRequest
     */
    'amount'?: PaymentprocessorMoney;
    /**
     * 
     * @type {PaymentprocessorCurrency}
     * @memberof PaymentprocessorPerformRefundRequest
     */
    'currency'?: PaymentprocessorCurrency;
}
