/* tslint:disable */
/* eslint-disable */
/**
 * Payment Processor Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface PaymentprocessorPaymentMethodRestrictionCondition
 */
export interface PaymentprocessorPaymentMethodRestrictionCondition {
    /**
     * 
     * @type {string}
     * @memberof PaymentprocessorPaymentMethodRestrictionCondition
     */
    'contextPath'?: string;
    /**
     * 
     * @type {ConditionAction}
     * @memberof PaymentprocessorPaymentMethodRestrictionCondition
     */
    'action'?: ConditionAction;
    /**
     * 
     * @type {PaymentMethodRestrictionConditionCondition}
     * @memberof PaymentprocessorPaymentMethodRestrictionCondition
     */
    'condition'?: PaymentMethodRestrictionConditionCondition;
    /**
     * 
     * @type {Array<string>}
     * @memberof PaymentprocessorPaymentMethodRestrictionCondition
     */
    'values'?: Array<string>;
}
