/* tslint:disable */
/* eslint-disable */
/**
 * Payment Processor Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface PaymentprocessorFinalizePaymentRequest
 */
export interface PaymentprocessorFinalizePaymentRequest {
    /**
     * 
     * @type {string}
     * @memberof PaymentprocessorFinalizePaymentRequest
     */
    'tenantId': string;
    /**
     * 
     * @type {string}
     * @memberof PaymentprocessorFinalizePaymentRequest
     */
    'paymentId': string;
    /**
     * 
     * @type {PaymentprocessorPaymentContext}
     * @memberof PaymentprocessorFinalizePaymentRequest
     */
    'context'?: PaymentprocessorPaymentContext;
    /**
     * payment type stripe, paypal..
     * @type {string}
     * @memberof PaymentprocessorFinalizePaymentRequest
     */
    'code': string;
    /**
     * 
     * @type {PaymentprocessorMoney}
     * @memberof PaymentprocessorFinalizePaymentRequest
     */
    'amount'?: PaymentprocessorMoney;
    /**
     * 
     * @type {PaymentprocessorCurrency}
     * @memberof PaymentprocessorFinalizePaymentRequest
     */
    'currency'?: PaymentprocessorCurrency;
    /**
     * 
     * @type {string}
     * @memberof PaymentprocessorFinalizePaymentRequest
     */
    'additionalInfo'?: string;
    /**
     * 
     * @type {Array<PaymentprocessorTransaction>}
     * @memberof PaymentprocessorFinalizePaymentRequest
     */
    'transactions'?: Array<PaymentprocessorTransaction>;
}
