/* tslint:disable */
/* eslint-disable */
/**
 * Payment Processor Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface PaymentprocessorCreatePaymentMethodRequest
 */
export interface PaymentprocessorCreatePaymentMethodRequest {
    /**
     * 
     * @type {string}
     * @memberof PaymentprocessorCreatePaymentMethodRequest
     */
    'tenantId': string;
    /**
     * 
     * @type {string}
     * @memberof PaymentprocessorCreatePaymentMethodRequest
     */
    'code': string;
    /**
     * 
     * @type {PaymentprocessorLocalizedText}
     * @memberof PaymentprocessorCreatePaymentMethodRequest
     */
    'title': PaymentprocessorLocalizedText;
    /**
     * 
     * @type {PaymentprocessorLocalizedText}
     * @memberof PaymentprocessorCreatePaymentMethodRequest
     */
    'label'?: PaymentprocessorLocalizedText;
    /**
     * 
     * @type {boolean}
     * @memberof PaymentprocessorCreatePaymentMethodRequest
     */
    'enabled'?: boolean;
    /**
     * 
     * @type {PaymentprocessorMoney}
     * @memberof PaymentprocessorCreatePaymentMethodRequest
     */
    'amount'?: PaymentprocessorMoney;
    /**
     * 
     * @type {PaymentprocessorCurrency}
     * @memberof PaymentprocessorCreatePaymentMethodRequest
     */
    'currency'?: PaymentprocessorCurrency;
    /**
     * 
     * @type {object}
     * @memberof PaymentprocessorCreatePaymentMethodRequest
     */
    'configuration'?: object;
    /**
     * 
     * @type {boolean}
     * @memberof PaymentprocessorCreatePaymentMethodRequest
     */
    'isUpfront'?: boolean;
    /**
     * 
     * @type {PaymentprocessorLocalizedText}
     * @memberof PaymentprocessorCreatePaymentMethodRequest
     */
    'description'?: PaymentprocessorLocalizedText;
    /**
     * 
     * @type {Array<PaymentprocessorPaymentMethodRestriction>}
     * @memberof PaymentprocessorCreatePaymentMethodRequest
     */
    'restrictions'?: Array<PaymentprocessorPaymentMethodRestriction>;
}
