/* tslint:disable */
/* eslint-disable */
/**
 * Payment Processor Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PaymentprocessorTransactionType = {
    Unknown: 'UNKNOWN',
    Authorization: 'AUTHORIZATION',
    Capture: 'CAPTURE',
    Sale: 'SALE',
    Refund: 'REFUND',
    Void: 'VOID',
    Failed: 'FAILED',
    Pending: 'PENDING',
    Fraud: 'FRAUD'
} as const;
export type PaymentprocessorTransactionType = typeof PaymentprocessorTransactionType[keyof typeof PaymentprocessorTransactionType];


export function PaymentprocessorTransactionTypeFromJSON(json: any): PaymentprocessorTransactionType {
    return PaymentprocessorTransactionTypeFromJSONTyped(json, false);
}

export function PaymentprocessorTransactionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentprocessorTransactionType {
    return json as PaymentprocessorTransactionType;
}

export function PaymentprocessorTransactionTypeToJSON(value?: PaymentprocessorTransactionType | null): any {
    return value as any;
}

