/* tslint:disable */
/* eslint-disable */
/**
 * Payment Processor Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface PaymentprocessorItem
 */
export interface PaymentprocessorItem {
    /**
     * 
     * @type {string}
     * @memberof PaymentprocessorItem
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentprocessorItem
     */
    'productGrn'?: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentprocessorItem
     */
    'qtyOrdered'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaymentprocessorItem
     */
    'qtyCommitted'?: number;
    /**
     * 
     * @type {PaymentprocessorMoney}
     * @memberof PaymentprocessorItem
     */
    'unitSalePrice'?: PaymentprocessorMoney;
    /**
     * 
     * @type {PaymentprocessorMoney}
     * @memberof PaymentprocessorItem
     */
    'unitListPrice'?: PaymentprocessorMoney;
    /**
     * 
     * @type {PaymentprocessorMoney}
     * @memberof PaymentprocessorItem
     */
    'unitBasePrice'?: PaymentprocessorMoney;
    /**
     * 
     * @type {PaymentprocessorMoney}
     * @memberof PaymentprocessorItem
     */
    'unitVatAmount'?: PaymentprocessorMoney;
    /**
     * 
     * @type {PaymentprocessorMoney}
     * @memberof PaymentprocessorItem
     */
    'rowSalePrice'?: PaymentprocessorMoney;
    /**
     * 
     * @type {PaymentprocessorMoney}
     * @memberof PaymentprocessorItem
     */
    'rowListPrice'?: PaymentprocessorMoney;
    /**
     * 
     * @type {PaymentprocessorMoney}
     * @memberof PaymentprocessorItem
     */
    'rowVatAmount'?: PaymentprocessorMoney;
    /**
     * 
     * @type {PaymentprocessorMoney}
     * @memberof PaymentprocessorItem
     */
    'discountAmount'?: PaymentprocessorMoney;
    /**
     * 
     * @type {PaymentprocessorMoney}
     * @memberof PaymentprocessorItem
     */
    'rowBasePrice'?: PaymentprocessorMoney;
    /**
     * 
     * @type {number}
     * @memberof PaymentprocessorItem
     */
    'vatPercentage'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PaymentprocessorItem
     */
    'vatInaccurate'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PaymentprocessorItem
     */
    'vatCalculated'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PaymentprocessorItem
     */
    'productName'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentprocessorItem
     */
    'productCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentprocessorItem
     */
    'productSku'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentprocessorItem
     */
    'productOptions'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentprocessorItem
     */
    'productImg'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentprocessorItem
     */
    'productData'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentprocessorItem
     */
    'shipmentInfoReference'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PaymentprocessorItem
     */
    'promotionGrn'?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof PaymentprocessorItem
     */
    'productIsVirtual'?: boolean;
}
