/**
 * Payment Processor Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PaymentprocessorTransactionType } from '../models/PaymentprocessorTransactionType';
import { HttpFile } from '../http/http';

export class PaymentprocessorTransaction {
    'paymentId': string;
    'id': string;
    'type'?: PaymentprocessorTransactionType;
    'additionalInfo'?: string;
    'childTransactions'?: Array<PaymentprocessorTransaction>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "paymentId",
            "baseName": "paymentId",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "PaymentprocessorTransactionType",
            "format": ""
        },
        {
            "name": "additionalInfo",
            "baseName": "additionalInfo",
            "type": "string",
            "format": ""
        },
        {
            "name": "childTransactions",
            "baseName": "childTransactions",
            "type": "Array<PaymentprocessorTransaction>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PaymentprocessorTransaction.attributeTypeMap;
    }

    public constructor() {
    }
}



