/**
 * Payment Processor Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PaymentContextOrderInfo } from '../models/PaymentContextOrderInfo';
import { PaymentprocessorPostalAddress } from '../models/PaymentprocessorPostalAddress';
import { HttpFile } from '../http/http';

export class PaymentprocessorPaymentContext {
    'billingAddress'?: PaymentprocessorPostalAddress;
    'shippingAddress'?: PaymentprocessorPostalAddress;
    'orderInfo'?: PaymentContextOrderInfo;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "billingAddress",
            "baseName": "billingAddress",
            "type": "PaymentprocessorPostalAddress",
            "format": ""
        },
        {
            "name": "shippingAddress",
            "baseName": "shippingAddress",
            "type": "PaymentprocessorPostalAddress",
            "format": ""
        },
        {
            "name": "orderInfo",
            "baseName": "orderInfo",
            "type": "PaymentContextOrderInfo",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PaymentprocessorPaymentContext.attributeTypeMap;
    }

    public constructor() {
    }
}

