/**
 * Payment Processor Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PaymentprocessorTransaction } from '../models/PaymentprocessorTransaction';
import { HttpFile } from '../http/http';

export class PaymentprocessorPayment {
    'id': string;
    /**
    * payment type stripe, paypal..
    */
    'code': string;
    'additionalInfo'?: string;
    'transactions'?: Array<PaymentprocessorTransaction>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "additionalInfo",
            "baseName": "additionalInfo",
            "type": "string",
            "format": ""
        },
        {
            "name": "transactions",
            "baseName": "transactions",
            "type": "Array<PaymentprocessorTransaction>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PaymentprocessorPayment.attributeTypeMap;
    }

    public constructor() {
    }
}

