/**
 * Payment Processor Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PaymentprocessorPaymentMethodRestrictionCondition } from '../models/PaymentprocessorPaymentMethodRestrictionCondition';
import { HttpFile } from '../http/http';

export class PaymentprocessorPaymentMethodRestriction {
    'conditions'?: Array<PaymentprocessorPaymentMethodRestrictionCondition>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "Array<PaymentprocessorPaymentMethodRestrictionCondition>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PaymentprocessorPaymentMethodRestriction.attributeTypeMap;
    }

    public constructor() {
    }
}

