/**
 * Payment Processor Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AvailabilityContextCustomer } from '../models/AvailabilityContextCustomer';
import { PaymentprocessorAvailabilityContextPostalAddress } from '../models/PaymentprocessorAvailabilityContextPostalAddress';
import { HttpFile } from '../http/http';

export class PaymentprocessorAvailabilityContext {
    'shippingAddress'?: PaymentprocessorAvailabilityContextPostalAddress;
    'billingAddress'?: PaymentprocessorAvailabilityContextPostalAddress;
    'customer'?: AvailabilityContextCustomer;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "shippingAddress",
            "baseName": "shippingAddress",
            "type": "PaymentprocessorAvailabilityContextPostalAddress",
            "format": ""
        },
        {
            "name": "billingAddress",
            "baseName": "billingAddress",
            "type": "PaymentprocessorAvailabilityContextPostalAddress",
            "format": ""
        },
        {
            "name": "customer",
            "baseName": "customer",
            "type": "AvailabilityContextCustomer",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PaymentprocessorAvailabilityContext.attributeTypeMap;
    }

    public constructor() {
    }
}

