/**
 * Payment Processor Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PaymentprocessorItem } from '../models/PaymentprocessorItem';
import { HttpFile } from '../http/http';

export class PaymentContextOrderInfo {
    'number': string;
    'grn': string;
    'items'?: Array<PaymentprocessorItem>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "number",
            "baseName": "number",
            "type": "string",
            "format": ""
        },
        {
            "name": "grn",
            "baseName": "grn",
            "type": "string",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<PaymentprocessorItem>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PaymentContextOrderInfo.attributeTypeMap;
    }

    public constructor() {
    }
}

