/**
 * Payment Processor Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum PaymentprocessorTransactionType {
    Unknown = 'UNKNOWN',
    Authorization = 'AUTHORIZATION',
    Capture = 'CAPTURE',
    Sale = 'SALE',
    Refund = 'REFUND',
    Void = 'VOID',
    Failed = 'FAILED',
    Pending = 'PENDING',
    Fraud = 'FRAUD'
}
