/**
 * Payment Processor Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PaymentprocessorAvailabilityContextPostalAddress {
    'regionCode'?: string;
    'postalCode'?: string;
    'firstname'?: string;
    'lastname'?: string;
    'addressLines'?: Array<string>;
    'additionalInfo'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "regionCode",
            "baseName": "regionCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "postalCode",
            "baseName": "postalCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstname",
            "baseName": "firstname",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastname",
            "baseName": "lastname",
            "type": "string",
            "format": ""
        },
        {
            "name": "addressLines",
            "baseName": "addressLines",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "additionalInfo",
            "baseName": "additionalInfo",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PaymentprocessorAvailabilityContextPostalAddress.attributeTypeMap;
    }

    public constructor() {
    }
}

