/**
 * Payment Processor Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PaymentprocessorCurrency } from '../models/PaymentprocessorCurrency';
import { PaymentprocessorMoney } from '../models/PaymentprocessorMoney';
import { PaymentprocessorPaymentContext } from '../models/PaymentprocessorPaymentContext';
import { PaymentprocessorTransaction } from '../models/PaymentprocessorTransaction';
import { HttpFile } from '../http/http';

export class PaymentprocessorFinalizePaymentRequest {
    'tenantId': string;
    'paymentId': string;
    'context'?: PaymentprocessorPaymentContext;
    /**
    * payment type stripe, paypal..
    */
    'code': string;
    'amount'?: PaymentprocessorMoney;
    'currency'?: PaymentprocessorCurrency;
    'additionalInfo'?: string;
    'transactions'?: Array<PaymentprocessorTransaction>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "paymentId",
            "baseName": "paymentId",
            "type": "string",
            "format": ""
        },
        {
            "name": "context",
            "baseName": "context",
            "type": "PaymentprocessorPaymentContext",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "PaymentprocessorMoney",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "PaymentprocessorCurrency",
            "format": ""
        },
        {
            "name": "additionalInfo",
            "baseName": "additionalInfo",
            "type": "string",
            "format": ""
        },
        {
            "name": "transactions",
            "baseName": "transactions",
            "type": "Array<PaymentprocessorTransaction>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PaymentprocessorFinalizePaymentRequest.attributeTypeMap;
    }

    public constructor() {
    }
}



