/**
 * Payment Processor Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConditionAction } from '../models/ConditionAction';
import { PaymentMethodRestrictionConditionCondition } from '../models/PaymentMethodRestrictionConditionCondition';
import { HttpFile } from '../http/http';

export class PaymentprocessorPaymentMethodRestrictionCondition {
    'contextPath'?: string;
    'action'?: ConditionAction;
    'condition'?: PaymentMethodRestrictionConditionCondition;
    'values'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "contextPath",
            "baseName": "contextPath",
            "type": "string",
            "format": ""
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "ConditionAction",
            "format": ""
        },
        {
            "name": "condition",
            "baseName": "condition",
            "type": "PaymentMethodRestrictionConditionCondition",
            "format": ""
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PaymentprocessorPaymentMethodRestrictionCondition.attributeTypeMap;
    }

    public constructor() {
    }
}



